// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltgdcqjcrxdgybkmhlmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Z2RjcWpjcnhkZ3lia21obG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTAzMTcsImV4cCI6MjA2OTQyNjMxN30.cJu1wbUJfba4JH3C9CCcZmV9pYD8DHmPRymacW_X4S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});